###
POST http://localhost:8080/api/v1/auth
Content-Type: application/json

{
  "firstname": "eam",
  "lastname": "dayan",
  "email": "eam.dayan@gmail.com",
  "password": "asd"
}

###
GET http://localhost:8080/api/v1/auth/confirm?token=c1bda6f2-5bd0-49cc-b7d8-86084fa65d3c