###
POST http://localhost:8080/api/v1/auth
Content-Type: application/json

{
  "firstname": "jon",
  "lastname": "snow",
  "email": "js@gmail.com",
  "password": "asd"
}

###
POST http://localhost:8080/api/v1/auth/confirm?token=8eb69636-f821-472e-a7ce-b6483d696678