spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true

#  mail:
#    host: localhost
#    port: 1025
#    username: hello
#    password: hello

  config:
    import: optional:file:.env[.properties]

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${GMAIL}
#    password: ${PASSWORD}
#    protocol: smtp
#    tls: true
#    properties.mail.smtp:
#      auth: true
#      starttls.enable: true
#      ssl.trust: smtp.gmail.com
#      connectiontimeoutL: 5000
#      timeout: 3000
#      writetimeout: 5000
